[platformio]
src_dir = main
build_dir = .pio/build

[env:xiao_c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = espidf
upload_port = COM24
monitor_port = COM24
monitor_speed = 115200
board_build.partitions = partitions.csv
upload_protocol = custom
upload_command = python -m esptool --chip esp32c6 --port $UPLOAD_PORT --baud 460800 write-flash --flash-mode dio --flash-freq 80m --flash-size 4MB 0x0 "$BUILD_DIR/bootloader.bin" 0x8000 "$BUILD_DIR/partitions.bin" 0xf000 "$BUILD_DIR/ota_data_initial.bin" 0x20000 "$BUILD_DIR/firmware.bin"
